### ISSUE TITLE
Strange warnings

### ISSUE THREAD

**Issue by guimard** [burak/CPAN-GD-SecurityImage#2]
Hello,

using your lib, I've this warning:
```
Argument " " isn't numeric in division (/) at /usr/share/perl5/GD/SecurityImage/Magick.pm line 81
```
The [corresponding code](https://github.com/burak/CPAN-GD-SecurityImage/blob/07300931ac10954296426a4c8d218fbab1c2d019/lib/GD/SecurityImage/Magick.pm#L81) is strange:
```perl
my $space = [$info->(q{ }), 0, q{ }]; # get " " parameters
my @randomy;
my $sy    = $space->[ASCENDER] || 1;
## no critic (ValuesAndExpressions::ProhibitMagicNumbers)
push @randomy,  $_, - $_ foreach $sy/2, $sy/4, $sy/8;
 ```
"ASCENDER" is a constant set to 2 and `$space->[ASCENDER]` is a true value:
```shell
$ perl -le 'print "true" if(" ")'
true
```
So `$sy` is always a space => it is normal to have this warning _(and I don't understand what is the goal of this loop)_.

Just after:
```perl
my @char; 
foreach ( split m{}xms, $key ) {
   push @char, [$info->($_), $self->random_angle, $_], $space, $space, $space;                            
}
my $total = 0;
   $total += $_->[WIDTH] foreach @char;                                                                   
```
produces:

    Use of uninitialized value in addition (+) at /usr/share/perl5/GD/SecurityImage/Magick.pm line 88,

Since WIDTH is set to 4 (constant), `$_->[WIDTH] == $space` which is a ref, not a number, so it's normal another time to have this warning.

**Comment by guimard** [comment]
The same part of code produces:

    Use of uninitialized value in multiplication (*) at /usr/share/perl5/GD/SecurityImage/Magick.pm line 90

Same analysis for me

**Comment by guimard** [comment]
It seems that sometimes for a strange reason, `$info->(q{ })` is empty

**Comment by guimard** [comment]
Is GD::SecurityImage maintained ?

**Comment by guimard** [comment]
[Found](https://gitlab.ow2.org/lemonldap-ng/lemonldap-ng/-/issues/2459), this library needs `gsfonts` package

**Comment by burak** [comment]
Hi, "ASCENDER" and such are named indices, so their value does not mean anything. You can think of this as a faster hash (well it is used on an arrayref that's for sure).

But anyways, I've added a documentation section for this in 1aa9993. However, I don't think it warrants a release just by itself. 

There is a `gdbox_empty()` method defined as a stub (to be compatible with GD, so, it doesn't do anything) for imagemagick but your problem sounds very similar to the issue one might hit with GD. Magick.pm can also evaluate the same situation perhaps, but I don't have time to look at it and the documentation should suffice for now.
