### ISSUE TITLE
Fails if Image::Magick is not installed 

### ISSUE THREAD

**Issue by andk** [burak/CPAN-GD-SecurityImage#3]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/101271375

Failing test: t/00-compile.t

All reports: http://analysis.cpantesters.org/reports_by_field?distv=GD-SecurityImage-1.74;field=qr%3A%28Can%27t%20locate%20%5CS%2Bpm%29

**Comment by burak** [comment]
Should be fixed after 1.75
