### ISSUE TITLE
Incorrect font width in CentOS 7.7 causes a display regression

### ISSUE THREAD

**Issue by maxbes** [burak/CPAN-GD-SecurityImage#4]
The following script:

```
use GD::SecurityImage use_magick => 1;

    my $image = GD::SecurityImage->new(
        width    => 220,
        height   => 40,
        lines    => 5,
        scramble => 1,
        rndmax   => 6,
    );

    $image->random;
    $image->create( 'normal', 'default', "#403030", '#FF644B');
    my ( $imageData, $mimeType, $rdm ) = $image->out( force => 'png' );

print $imageData;
```

Worked fine with CentOS 7.6 but since migrating to 7.7, the `scramble` option now generates unreadable Captchas

7.6: 
![image](https://user-images.githubusercontent.com/46450505/67032557-1c6c2480-f114-11e9-8382-242b1621dbda.png)

7.7: 
![image](https://user-images.githubusercontent.com/46450505/67032588-29891380-f114-11e9-9493-82278ea4dc45.png)

(the captchas look fine, without the scramble option)

After some investigation, I discovered that QueryFontMetrics started reporting very wide font width when run on a single space string (but not on other strings). The other digit characters are thus rendered out of image boundaries.

Forcing certain fonts (`font => 'DejaVu-Sans-Book'`) gets rid of the issue, assuming the user can figure out what to specify as a font name.. It would be best if the module worked fine with the system's default font.

I realize that the issue probably does not lie within this module, but I'm having trouble figure out what component to blame exactly. Downgrading ImageMagick does not restore the 7.6 behavior, so it's probably something in the font system but I have no idea where to look.

**Comment by burak** [comment]
I wonder whether you need to update gsfonts as in #2. But in any case, I can't replicate the issue on my system (macos). But indeed seems to be something to do with your environment.
